In [1]:
import pandas as pd
import matplotlib.pyplot as plt

# Charger le fichier Excel
df = pd.read_excel('BASE FUSIONNEE CDT 4 MAI.xlsx')

# Afficher les premières lignes du DataFrame pour vérifier l'importation
print(df.head())

# Statistiques descriptives pour les données numériques
print(df.describe())

  Anonymisation Hopital                 ddn            datechir        Age  \
0       HEGP002    HEGP 1998-12-22 01:00:00 2015-01-08 01:00:00  16.057534
1       HEGP003    HEGP 1952-02-15 01:00:00 2015-07-27 02:00:00  63.487671
2       HEGP004    HEGP 1996-01-21 01:00:00 2015-12-07 01:00:00  19.890411
3       HEGP005    HEGP 1961-03-04 01:00:00 2015-08-02 02:00:00  54.449315
4       HEGP006    HEGP 1976-11-29 01:00:00 2015-09-18 02:00:00  38.827397

   sexe  poids        bmi  hta  diabete  ...  Delai_DC  deces  DC_J90  \
0     0   56.0  24.888889    0        0  ...       2.0      1       1
1     1   90.0  31.141869    0        0  ...       NaN      0       0
2     0   41.0  16.015625    0        0  ...      15.0      1       1
3     1   86.0  33.593750    1        0  ...       NaN      1       0
4     1   76.0  23.456790    1        0  ...       NaN      0       0

   DC_J365  DC_J1825  mort1an  mort5ans  Delai_DC_J90  Delai_DC_J365  \
0        1         1      1.0       1.0           2.0            2.0
1        0         0      0.0       0.0          90.0          365.0
2        1         1      1.0       1.0          15.0           15.0
3        0         0      NaN       NaN          90.0          365.0
4        0         0      0.0       0.0          90.0          365.0

   Delai_DC_J1825
0             2.0
1          1825.0
2            15.0
3          1825.0
4          1825.0

[5 rows x 117 columns]
              Age        sexe       poids         bmi         hta     diabete  \
count  609.000000  609.000000  609.000000  609.000000  609.000000  609.000000
mean    52.239035    0.766831   76.089491   26.249002    0.338259    0.228243
std     12.446493    0.423197   16.609182    5.038666    0.473506    0.420045
min     16.057534    0.000000   32.000000   14.222222    0.000000    0.000000
25%     45.068493    1.000000   64.000000   22.724403    0.000000    0.000000
50%     54.547945    1.000000   75.000000   25.617284    0.000000    0.000000
75%     61.964384    1.000000   87.000000   29.320988    1.000000    0.000000
max     75.676712    1.000000  140.000000   50.000000    1.000000    1.000000

         dyslipid        aomi        bpco         irc  ...    Delai_DC  \
count  609.000000  609.000000  609.000000  609.000000  ...   205.00000
mean     0.280788    0.108374    0.106732    0.326765  ...   312.34126
std      0.449754    0.311108    0.309026    0.469416  ...   458.78732
min      0.000000    0.000000    0.000000    0.000000  ...     0.00000
25%      0.000000    0.000000    0.000000    0.000000  ...    16.00000
50%      0.000000    0.000000    0.000000    0.000000  ...    76.00000
75%      1.000000    0.000000    0.000000    1.000000  ...   445.00000
max      1.000000    1.000000    1.000000    1.000000  ...  2017.00000

            deces     DC_J90     DC_J365    DC_J1825     mort1an    mort5ans  \
count  609.000000  609.00000  609.000000  609.000000  595.000000  277.000000
mean     0.334975    0.17734    0.234811    0.330049    0.215126    0.631769
std      0.472370    0.38227    0.424229    0.470617    0.411256    0.483198
min      0.000000    0.00000    0.000000    0.000000    0.000000    0.000000
25%      0.000000    0.00000    0.000000    0.000000    0.000000    0.000000
50%      0.000000    0.00000    0.000000    0.000000    0.000000    1.000000
75%      1.000000    0.00000    0.000000    1.000000    0.000000    1.000000
max      1.000000    1.00000    1.000000    1.000000    1.000000    1.000000

       Delai_DC_J90  Delai_DC_J365  Delai_DC_J1825
count    609.000000     609.000000      609.000000
mean      78.244595     294.198618     1314.999932
std       27.058510     133.824533      762.545723
min        0.000000       0.000000        0.000000
25%       90.000000     365.000000      441.000000
50%       90.000000     365.000000     1825.000000
75%       90.000000     365.000000     1825.000000
max       90.000000     365.000000     1825.000000

[8 rows x 110 columns]